variables:
  IQ_CLI_VERSION: 1.45.0
  IMAGE_TAG: $CI_REGISTRY_IMAGE:${IQ_CLI_VERSION}
  IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest

build-docker:
  stage: build
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker build --tag $IMAGE_TAG --build-arg IQ_VERSION=${IQ_CLI_VERSION}-01 .
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
  only:
    - tags
